module.exports = {
  'likes': '{ likes, number } me gusta',
  'logout': 'Salir',
  'english': 'Inglés',
  'spanish': 'Español',
  'signup.subheading': 'Crear un nuevo usuario',
  'signup.facebook': 'Iniciar sesión con Facebook',
  'signup.text': 'Iniciar sesión',
  'email': 'Correo electrónico',
  'username': 'Nombre de usuario',
  'fullname': 'Nombre completo',
  'password': 'Contraseña',
  'signup.call-to-action': 'Regístrate',
  'signup.have-account': '¿Tienes una cuenta?',
  'signin': 'Entrar',
  'signin.not-have-account': '¿No tienes una cuenta?',
  'language': 'Idioma',
  'upload-picture': 'Subir foto',
  'upload': 'Subir',
  'selectText': 'Seleccione uno',
  'gender': 'Género',
  'man': 'Hombre',
  'woman': 'Mujer',
  'address': 'Dirección',
  'email': 'Email',
  'phone': 'Teléfono',
  'otherPhone': 'Otro teléfono',
  'save': 'Guardar',
  'cancel': 'Cancelar',
  'clientName': 'Nombre del cliente',
  'name': 'Nombre',
  'pet': 'Mascota',
  'edit': 'Editar',
  'race': 'Raza',
  'color': 'Color',
  'status': 'Estatus',
  'age': 'Edad',
  'ethnicity': 'Etnia',
  'male': 'Macho',
  'female': 'Hembra',
  'borndate': 'Fecha de Nacimiento',
  'weight': 'Peso',
  'ok': 'Ok',
  'death': 'Fallecido'


}